### ISSUE TITLE
Timezone propTypes errors on `main`

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#10015]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Build `main` app and run it with JS console open

## Expected Result:

No console errors

## Actual Result:

![2022-07-19_11-34-02](https://user-images.githubusercontent.com/32969087/179852651-20c28dca-ad80-43ab-bb83-4355b6bdaccb.png)
![2022-07-19_11-34-24](https://user-images.githubusercontent.com/32969087/179852657-7018fb0c-06aa-44ad-9cd0-f116462a820b.png)

## Workaround:

Unsure if this is happening on staging.

## Platform:
- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** Unsure
**Reproducible in production?:** Unsure
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I think it's most likely this was introduced by the Web-Expensify changes [here](https://github.com/Expensify/Web-Expensify/pull/34321). Looking at the data in Onyx and we have this:

![2022-07-19_11-38-49](https://user-images.githubusercontent.com/32969087/179853159-1b6553a1-8474-479b-82ab-255d4e2b0561.png)

Doesn't seem like this is breaking anything though.

If a user has no timezone maybe it is better to just default to:

```
DEFAULT_TIME_ZONE: {automatic: true, selected: 'America/Los_Angeles'},
```

Maybe something @roryabraham can tackle as part of https://github.com/Expensify/Expensify/issues/219198

**Comment by roryabraham** [comment]
Dropping this

**Comment by marcaaron** [comment]
I think this was actually fixed recently by @chiragsalian in https://github.com/Expensify/Web-Expensify/pull/34602

Noticed this -> https://github.com/Expensify/Web-Expensify/blob/6258d9e68bbf8473bf1be1b68b14c8374da5e35b/lib/PersonalDetail.php#L189-L192

**Comment by parasharrajat** [comment]
This is back. 

```
react.development.js?72d0:207 Warning: Failed prop type: Invalid prop `personalDetails.jack@expensify.com.timezone.automatic` of type `string` supplied to `WithCurrentUserPersonalDetails(Component)`, expected `boolean`.
    at WithCurrentUserPersonalDetails (webpack-internal:///./src/components/withCurrentUserPersonalDetails.js:32:34)
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2462:73)
    at withPersonalDetails(Component)
    at withNetwork(withPersonalDetails(Component))
    at withLocalize(withNetwork(withPersonalDetails(Component)))
    at WithNavigationFocus (webpack-internal:///./src/components/withNavigationFocus.js:23:91)
    at WithDrawerState (webpack-internal:///./src/components/withDrawerState.js:23:92)
    at withWindowDimensions(Component)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at OfflineWithFeedback (webpack-internal:///./src/components/OfflineWithFeedback.js:101:85)
    at withNetwork(OfflineWithFeedback)
    at withLocalize(withNetwork(OfflineWithFeedback))
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///./src/components/SwipeableView/index.js:6:23)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at ReportFooter (webpack-internal:///./src/pages/home/report/ReportFooter.js:91:86)
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2462:73)
    at withWindowDimensions(Component)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at FullPageNotFoundView (webpack-internal:///./src/components/BlockingViews/FullPageNotFoundView.js:58:13)
    at withLocalize(FullPageNotFoundView)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at KeyboardAvoidingView (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/KeyboardAvoidingView/index.js:42:86)
    ```
