### ISSUE TITLE
Search page shows blank list after login while trying to open that deeplink url reported by @0xmiroslav 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12717]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Logout if already logged in
2. Visit https://new.expensify.com/search
3. Login with any account

## Expected Result: 
Search page shows with contacts list

## Actual Result: 
Search page shows but no content

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201743472-01434ae5-ea2e-441d-932e-6e819fed5807.mp4

https://user-images.githubusercontent.com/43996225/201743507-7631963f-9ca2-4e5b-9b29-e7aa8c10f42c.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668427738763249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment]
I was able to pull up the search with contact list. However I did get an error message before this. @kavimuru are you still able to reproduce this one?

https://user-images.githubusercontent.com/8292562/202036483-95373a8d-299e-4470-bd4b-0b661b20dcf3.mov

**Comment by kavimuru** [comment]
@tjferriss I'm still able to reproduce

https://user-images.githubusercontent.com/43996225/202038217-58b81f2c-d10d-4e85-aaec-f6138e86b879.mp4

**Comment by tjferriss** [comment]
Here you go:
<img width="1302" alt="Screen Shot 2022-11-15 at 2 39 48 PM" src="https://user-images.githubusercontent.com/8292562/202039975-418db0f9-a298-4043-a8dc-6a990c18b9d2.png">


```
react-dom.production.min.js:186 TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.removeSMSDomain (str.js:934:21)
    at S (OptionsListUtils.js:351:19)
    at OptionsListUtils.js:499:31
    at Function.zt (each.js:14:7)
    at w (OptionsListUtils.js:483:5)
    at Object.H (OptionsListUtils.js:650:12)
    at new I (SearchPage.js:60:13)
    at bi (react-dom.production.min.js:140:172)
    at Fl (react-dom.production.min.js:216:146)
    at yc (react-dom.production.min.js:291:286)
ll @ react-dom.production.min.js:186
gestureStateManager.ts:22 Uncaught Error: No handler for tag 3
    at Q (NodeManager.ts:12:9)
    at Object.updateGestureHandler (RNGestureHandlerModule.web.ts:108:7)
    at GestureDetector.tsx:181:7
    at e.exports (_invoke.js:5:25)
    at C.<computed> (_task.js:35:7)
    at Number.A (_task.js:21:5)
    at MessagePort.h (_task.js:25:7)
search:1          Failed to load resource: the server responded with a status of 404 ()
```

**Comment by JmillsExpensify** [comment]
Looking at the video, it looks like the bug is more accurately that we're showing a blank list while loading, rather than persisting a spinner while that same list is being loaded. In fact, the results show up at the end of that video, right?

**Comment by tjferriss** [comment]
I'm on v1.2.28-2

**Comment by tjferriss** [comment]
Ok I was finally able to replicate this when in incognito so I'm going to add the External tag to get us started. 

However, I also read up on the referenced [bug issue](https://github.com/Expensify/App/issues/12719), it looks like there might be a wider solution for these types of issues being discussed there.

**Comment by mountiny** [comment]
Putting this on hold for the navigation refactor as also Rajat mentione this seems like an issue with react-navigation https://github.com/Expensify/App/issues/11768

**Comment by JmillsExpensify** [comment]
Apologies @tjferriss but I'm going to take this over since it's not part of the larger react navigation refactor. I'm the BZ helping manage all the related issues.

**Comment by mountiny** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Still on hold for the larger linked initiative. Also removed the Help Wanted and External labels in the meantime.

**Comment by JmillsExpensify** [comment]
Still on hold for the larger react navigation re-write.

**Comment by JmillsExpensify** [comment]
Still on hold for the navigation re-write.

**Comment by JmillsExpensify** [comment]
Still on hold for navigation revamp.

**Comment by JmillsExpensify** [comment]
Switched our weekly for monthly given that this is a larger project that has no defined ETA.

**Comment by JmillsExpensify** [comment]
Still on hold for the navigation project.

**Comment by mountiny** [comment]
On hold

**Comment by mountiny** [comment]
on hold

**Comment by mountiny** [comment]
on hold

**Comment by JmillsExpensify** [comment]
Thanks @mountiny. Still working on clearing a super long GH backlog, should be in good shape for the next time around. 🙌🏼

**Comment by JmillsExpensify** [comment]
Still on hold

**Comment by mountiny** [comment]
Lets do that @JmillsExpensify

**Comment by mountiny** [comment]
Jason is ooo, reassinging to handle the payments

**Comment by mountiny** [comment]
Reporting bonus of $250 is due for @0xmiroslav thanks @twisterdotcom

**Comment by twisterdotcom** [comment]
Offer sent: https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/24794793
