### ISSUE TITLE
Non-fatal crash on .cutBefore

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#21168]
I'm seeing this crash report on Crashlytics:

```
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: Cannot read property 'indexOf' of undefined
       at .cutBefore(address at index.android.bundle:1:1030147)
       at .extractEmailDomain(address at index.android.bundle:1:1030770)
       at .isExpensifyTeam(address at index.android.bundle:1:4109066)
       at .anonymous(address at index.android.bundle:1:4433025)
       at .apply((native):0:0)
       at .anonymous(address at index.android.bundle:1:1021004)
       at .anonymous(address at index.android.bundle:1:1022610)
       at .each(address at index.android.bundle:1:1022145)
       at .filter(address at index.android.bundle:1:1022584)
       at .reject(address at index.android.bundle:1:1022672)
       at .render(address at index.android.bundle:1:4432654)
       at .finishClassComponent(address at index.android.bundle:1:367940)
       at .updateClassComponent(address at index.android.bundle:1:367801)
       at .beginWork$1(address at index.android.bundle:1:401149)
       at .performUnitOfWork(address at index.android.bundle:1:387954)
       at .workLoopSync(address at index.android.bundle:1:387815)
       at .renderRootSync(address at index.android.bundle:1:387699)
       at .performSyncWorkOnRoot(address at index.android.bundle:1:385116)
       at .flushSyncCallbacks(address at index.android.bundle:1:349437)
       at .scheduleUpdateOnFiber(address at index.android.bundle:1:382255)
       at .enqueueSetState(address at index.android.bundle:1:397598)
       at .anonymous(address at index.android.bundle:1:123199)
       at ._loop2(address at index.android.bundle:1:1003158)
       at .keyChanged(address at index.android.bundle:1:1002926)
       at .anonymous(address at index.android.bundle:1:1005438)
       at .tryCallOne(InternalBytecode.js:53:16)
       at .anonymous(InternalBytecode.js:139:27)
       at .apply((native):0:0)
       at .anonymous(address at index.android.bundle:1:236529)
       at ._callTimer(address at index.android.bundle:1:235475)
       at ._callReactNativeMicrotasksPass(address at index.android.bundle:1:235640)
       at .callReactNativeMicrotasks(address at index.android.bundle:1:237628)
       at .__callReactNativeMicrotasks(address at index.android.bundle:1:138882)
       at .anonymous(address at index.android.bundle:1:137972)
       at .__guard(address at index.android.bundle:1:138723)
       at .flushedQueue(address at index.android.bundle:1:137883)
```

Seems to come from [these lines](https://github.com/Expensify/App/blob/116abf58876038cb102d94477c95ebb504a93c96/src/pages/workspace/WorkspaceMembersPage.js#L381-L382).

cc @Li357 since I see you on the blame for those lines.

**Comment by Li357** [comment]
Hmm, I refactored the component to a function and kept the logic the same. Maybe `member.login` is undefined in `PolicyUtils.isExpensifyTeam(member.login)` as part of secure logins project, and we should use `accountID` instead?

**Comment by sophiepintoraetz** [comment]
@luacmartins - what's needed from me on this?

**Comment by luacmartins** [comment]
I haven't seen any crashes on the latest staging version, so it was probably fixed in that commit. I'll reopen this if I see any new occurrence. Thanks for investigating!
