### ISSUE TITLE
Android - Attachment - Application crashes after downloading attachments few times

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to any account
2. Open any chat that has attachment
3. Download any attachment
4. Repeat the step 3

## Expected Result:
Attachment should be downloaded successfully

## Actual Result:
Application crashes after downloading attachments few times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7add8041-49c5-49b7-aeed-27c5b1f39600

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688487608622279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
Cannot reproduce

https://github.com/Expensify/App/assets/14225673/a24fe2e4-c3fb-4e7f-9356-fc3ea00c1adb

**Comment by tranvantoan-qn** [comment]
@anmurali did you check with the same Device and OS version as I mentioned in the report? :
- Oppo Reno 8
- Android 13

**Comment by tranvantoan-qn** [comment]
This is the crash log for more details:
`FATAL EXCEPTION: main
Process: com.expensify.chat, PID: 26756
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x80010 pkg=com.expensify.chat (has extras) } in com.ReactNativeBlobUtil.ReactNativeBlobUtilReq@e07b18a
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1920)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8364)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:26)
	at com.ReactNativeBlobUtil.ReactNativeBlobUtilReq.onReceive(ReactNativeBlobUtilReq.java:911)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1885)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2) 
	at android.os.Handler.handleCallback(Handler.java:942) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loopOnce(Looper.java:240) 
	at android.os.Looper.loop(Looper.java:351) 
	at android.app.ActivityThread.main(ActivityThread.java:8364) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) `
