### ISSUE TITLE
[$500] Investigate Android crash Cannot read property 'nativeEvent' of undefined

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26818]
Link to [firebase](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/022302da0d55dfb152b0c7d7d51a24a7?time=last-seven-days&types=crash&versions=1.3.63-0%20(1001036300)&sessionEventKey=64F733BB03340001361C141DE7BFC150_1853786251600028066)

```
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'nativeEvent' of undefined, js engine: hermes, stack:
_continue@1:4144607
onPress@1:4138384
onPress@1:4133987
anonymous@1:1603000
anonymous@1:1645144
every@1:817184
bindHandlerToKeydownEvent@1:1645040
anonymous@1:1607970
listener@1:977187
emit@1:157568
__callFunction@1:166260
anonymous@1:164612
__guard@1:165565
callFunctionReturnFlushedQueue@1:164570

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:920)
```

Happening on Samsung, version 1.3.63
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f973d2fc68f42aa1</li>
        <li>Upwork Job ID: 1699121126005202944</li>
        <li>Last Price Increase: 2023-09-12</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
Looking for proposals

**Comment by mountiny** [comment]
Based on the comment above from @allroundexperts this should be resolved, closing
