### ISSUE TITLE
`Set up git for OSBotify` can fail

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#32069]
## Problem

The GitHub workflow `Set up git for OSBotify` step can fail with this error:

```
Run actions/create-github-app-token@9d97a4282b2c51a2f4f0465b9326399f53c890d4
  with:
    app-id: ***
    private-key: ***
  
owner and repositories not set, creating token for the current repository ("App")
RequestError [HttpError]: 'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued
    at /Users/runner/work/_actions/actions/create-github-app-token/9d97a4282b2c51a2f4f0465b9326399f53c890d4/dist/main.cjs:2890:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/Users/runner/work/_actions/actions/create-github-app-token/9d97a4282b2c51a2f4f0465b9326399f53c890d4/dist/main.cjs:10050:22) {
  status: 401,
  response: {
    url: 'https://api.github.com/repos/Expensify/App/installation',
    status: 401,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-length': '161',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 27 Nov 2023 18:54:47 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=315[36](https://github.com/Expensify/App/actions/runs/7009500974/job/19068097372#step:4:41)000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'A[41](https://github.com/Expensify/App/actions/runs/7009500974/job/19068097372#step:4:47)C:8C08:2D5547:2ED9[46](https://github.com/Expensify/App/actions/runs/7009500974/job/19068097372#step:4:52):6564E5F7',
      'x-xss-protection': '0'
    },
    data: {
      message: "'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued",
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/Expensify/App/installation',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/create-github-app-token',
      authorization: 'bearer [REDACTED]'
    }
  }
}
```

## Solution
Fix it and make it more reliable so it doesn't fail
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ee9a3333f9bff2d</li>
        <li>Upwork Job ID: 1729225052675010560</li>
        <li>Last Price Increase: 2023-11-27</li>
    </ul>
</details>

**Comment by AndrewGable** [comment]
@justinpersaud said he would look into this one 👍

**Comment by justinpersaud** [comment]
No update

**Comment by justinpersaud** [comment]
Was finishing up migrating Mobile-Deploy to GHA

**Comment by justinpersaud** [comment]
PR up for review

**Comment by Julesssss** [comment]
Merged. Seems to be working well so far 🤞

**Comment by justinpersaud** [comment]
Cool. Going to close this then and we can reopen if it is still an issue.
