### ISSUE TITLE
[$500] Android - App crashes , unable to open the app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33277]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1.Tap on the app

Or

Pre-condition Delete all cookies and clear all data
1. Launch app
2. Enter credentials

## Expected Result:
User must be able to open the app

## Actual Result:
App crashes when user tries to login or open

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7d2fd560-53c4-420b-9987-68ec8521a815

https://github.com/Expensify/App/assets/115492554/1c012bfd-a380-4ab0-9b55-658063c93080

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107238d94e6064e6c</li>
        <li>Upwork Job ID: 1737067250945007616</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Here's the native Stacktrace, seems to come from the reanimated lib

```
Fatal Exception: com.facebook.jni.CppException: Exception in HostFunction: java.lang.ClassCastException: java.lang.Double cannot be cast to com.facebook.react.bridge.ReadableMap

Error: Exception in HostFunction: java.lang.ClassCastException: java.lang.Double cannot be cast to com.facebook.react.bridge.ReadableMap
    at _updatePropsPaper (native)
    at flush (JavaScript:1:349)
    at anonymous (JavaScript:1:350)
    at callMicrotasksOnUIThread (JavaScript:1:61)
    at anonymous (JavaScript:1:139)
       at com.swmansion.reanimated.AndroidUIScheduler.triggerUI(AndroidUIScheduler.java)
       at com.swmansion.reanimated.AndroidUIScheduler$1.run(AndroidUIScheduler.java:24)
       at com.swmansion.reanimated.AndroidUIScheduler$2.runGuarded(AndroidUIScheduler.java:43)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:30)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8194)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by Julesssss** [comment]
I shared with SWM [here](https://expensify.slack.com/archives/C04878MDF34/p1702985316746889).

**Comment by Julesssss** [comment]
[This PR](https://github.com/Expensify/App/pull/33224) is attempting to resolve the issue

**Comment by rushatgabhane** [comment]
If not resolved in time, reverting the culprit PR https://github.com/Expensify/App/pull/26654 should get the job done

**Comment by Julesssss** [comment]
Thanks, I might do that.

**Comment by rushatgabhane** [comment]
https://github.com/Expensify/App/pull/33224 is ready. I'm gonna retest before we can merge
