### ISSUE TITLE
Investigate App Crash MainActivity.onCreate

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35655]
On the `1.4.35-5` build we have got 3 crashes on the OnePlus8Pro device:

<img width="836" alt="image" src="https://github.com/Expensify/App/assets/36083550/7344b9ae-7b62-4304-80cd-074a4dfec58a">

With the following logs:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.expensify.chat/com.expensify.chat.MainActivity}: java.lang.reflect.InvocationTargetException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3433)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

And 

```
Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at expo.modules.ReactActivityDelegateWrapper.invokeDelegateMethod(ReactActivityDelegateWrapper.kt:309)
       at expo.modules.ReactActivityDelegateWrapper.loadApp(ReactActivityDelegateWrapper.kt:112)
       at expo.modules.ReactActivityDelegateWrapper.onCreate(ReactActivityDelegateWrapper.kt:154)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
       at com.expensify.chat.MainActivity.onCreate(MainActivity.kt:36)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1548)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3406)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

or:

```
Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libjsi.so caused by: couldn't find DSO to load: libfolly_runtime.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.expensify.chat/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0 result: 0 result: 0 result: 0 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1228)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:1044)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:956)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:903)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:869)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:24)
       at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:380)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:326)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:98)
       at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:32)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:43)
       at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:173)
       at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:123)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at expo.modules.ReactActivityDelegateWrapper.invokeDelegateMethod(ReactActivityDelegateWrapper.kt:309)
       at expo.modules.ReactActivityDelegateWrapper.loadApp(ReactActivityDelegateWrapper.kt:112)
       at expo.modules.ReactActivityDelegateWrapper.onCreate(ReactActivityDelegateWrapper.kt:154)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
       at com.expensify.chat.MainActivity.onCreate(MainActivity.kt:36)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1548)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3406)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by yoyumiracle** [comment]
I think there problem with libc++_share.so file. Please pay attention to EM_AARCH64 (183) instead of EM_X86_64 (62). I think if use EM_X86_64 libc++_share.so file will solve problem. Thank you.

**Comment by yoyumiracle** [comment]
Contributor details
Your Expensify account email: peraivan10@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010e420e4da95306da

I think there problem with libc++_share.so file. Please pay attention to EM_AARCH64 (183) instead of EM_X86_64 (62). I think if use EM_X86_64 libc++_share.so file will solve problem. Thank you.

**Comment by yoyumiracle** [comment]
allprojects {
    repositories {
        google()
        center()
		...

        // force dependency versions on all subprojects
        configurations.all {
            resolutionStrategy {

                // use 0.9.0 to fix crash on Android 11
                force "com.facebook.soloader:soloader:0.9.0"
			}
		}
	}
}

I think it would be solve problem.

**Comment by yoyumiracle** [comment]
`allprojects {
    repositories {
        google()
        center()
		...

        // force dependency versions on all subprojects
        configurations.all {
            resolutionStrategy {

                // use 0.9.0 to fix crash on Android 11
                force "com.facebook.soloader:soloader:0.9.0"
			}
		}
	}
}`

I think it would be solve problem.

**Comment by yoyumiracle** [comment]
higher soloader version like I explained above

**Comment by akinwale** [comment]
Seems rather similar to https://github.com/facebook/react-native/issues/41372.

@yoyumiracle Please create a proposal following the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md). You can also have a look at the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to have an idea of how to contribute. Thanks.

**Comment by akinwale** [comment]
> I can't understand exactly. @akinwale Can I have further detail about proposal, It will thankful if you give me an example.

When proposing a solution for t he issue, it should follow this format: https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/PROPOSAL_TEMPLATE.md

You can copy the template, edit it with the details of your solution, and then paste it as a comment on the issue.

Hope this helps.

**Comment by yoyumiracle** [comment]
1. The issue is runtime error occured when load the libc++_shared library.
2. It, the root cause maybe concern with facebook's soloader version problem.
3. I suggest that version up the facebook's soloader by following below explanation.
       force "com.facebook.soloader:soloader:0.9.0" to build.gradle file.

**Comment by akinwale** [comment]
@yoyumiracle Please take these steps to post a proposal in the correct format.

1. Copy the text from https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/PROPOSAL_TEMPLATE.md
2. Paste it into a new comment on this issue.
3. Edit it with details of your solution (the cause, and how to fix).
4. Post the comment.

**Comment by mountiny** [comment]
Hello Petar @yoyumiracle You must follow this template https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/PROPOSAL_TEMPLATE.md for proposals. 

Can you please stop posting comments until you formulate the proposal in expected format? thank you!

**Comment by yoyumiracle** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
      . On the 1.4.35-5 build we have got 3 crashes on the OnePlus8Pro device

### What is the root cause of that problem?
      . Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libjsi.so caused by: couldn't find DSO to load: libfolly_runtime.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.expensify.chat/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0 result: 0 result: 0 result: 0 result: 0

### What changes do you think we should make in order to solve the problem?
      . I think it caused by facebooksoloader version is unmatched to device. So recommend that version up the facebooksoloader using this. 
        force "com.facebook.soloader:soloader:0.9.0" to build.gradle file.


Sorry for confuse

**Comment by akinwale** [comment]
We can move forward with @yoyumiracle's [proposal](https://github.com/Expensify/App/issues/35655#issuecomment-1932592472) here. Based on [Google's recommendation](https://support.google.com/faqs/answer/12576726), the soloader version should be 0.10.4+.

@yoyumiracle Please use `com.facebook.soloader:soloader:0.10.4+` instead of `0.9.0` when creating your PR.

@mountiny After the PR is created, a build needs to be generated that can be tested using browserstack, or by someone who has a physical device, since I do not own a OnePlus 8 Pro.

🎀👀🎀 C+ reviewed.

**Comment by yoyumiracle** [comment]
Which branch I have to fork?

**Comment by akinwale** [comment]
> Which branch I have to fork?

You can create a fork of the https://github.com/Expensify/App on the main branch.

**Comment by yoyumiracle** [comment]
I have created PR. Title: "Investigate App Crash MainActivity.onCreate"

**Comment by jeremy-croff** [comment]
The proposal for this issue is very vague. Root cause is a copy paste of the stack trace?
Additionally, there are numerous reports of this workaround not fixing the issue. And there's many others having this issue on RN:
https://github.com/facebook/SoLoader/issues/59#issuecomment-1546528130

This is definetely an upstream issue. But we can continue to try to find a workaround.

**Comment by akinwale** [comment]
> Additionally, there are numerous reports of this workaround not fixing the issue on the later RN versions like we are running. [facebook/SoLoader#59 (comment)](https://github.com/facebook/SoLoader/issues/59#issuecomment-1546528130)
> 
> This is definitely an upstream issue. But we can continue to try to find a workaround.
> 
> I went into RN commit history to see what version of soLoader they have for RN@73.2( our current version) and it's also using 10.5 for soLoader https://github.com/facebook/react-native/blob/d2ac5d6a55ab0cd3a32c6939b941b31f06ea32e8/packages/react-native/gradle/libs.versions.toml#L30 So my hopes for the PR working is very low.

Thanks for the insight.

If the fix doesn't work, looks like we may need to wait for more proposals until we find one that actually fixes the issue. I'll do some more research on the issue in the mean time.

cc @marcaaron @mountiny

**Comment by yoyumiracle** [comment]
Jeremy are you kid? Yeah, It will be emulator. In manually real device  not use x86 architecture maybe. But it doesn't matter. Issue occured and solve is our task. The Expensify is stand for this, I think. There's no need to talking about it's a emulator or real device.
That's waste time if you have problem, you suggest an issue on Expensify then any body will propose for solve the issue.
I don't mind even my github blocked, it's my opinion. Thanks.

**Comment by mountiny** [comment]
We can also wait a week and see if this is still happening

**Comment by yoyumiracle** [comment]
@mountiny May I ask that proposal I suggested is right or not? 
I made pull request about 5 days ago as bot notice but it doesn't approve till now.
Reviewer @danieldoglas never answer for the reason.
I think I never do such a thing harmful to Expensify. This makes me to feel confuse.
If you introduce the reason this, it will be thankful.
Thanks.

**Comment by yoyumiracle** [comment]
I create PR

**Comment by yoyumiracle** [comment]
> 📣 @akinwale 🎉 An offer has been automatically sent to your Upwork account for the Contributor role 🎉 Thanks for contributing to the Expensify app!
> 
> [Offer link](https://www.upwork.com/nx/wm/offer/) [Upwork job](https://www.upwork.com/jobs/~01d0d2e521d108526a) Please accept the offer and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

@akinwale Thanks for your offer, but I can't find any automated offer on my Upwork account, and the offer link mentioned above is not working properly. Please check it again and shoot me your reply, cheers!

**Comment by yoyumiracle** [comment]
Sorry @marcaaron, @akinwale.
I tried to solve conflict but that I made a mistake that close PR. So I recreate the PR.
Really sorry.

**Comment by Gautham495** [comment]
I am getting the same exact same error in my own production application in the appstores. I gave up on using codepush because of this on android.  There is no available solution to this on the internet and I genuinely feel the oneplus 8 is a defective modal with green lines in the middle (Saw in many youtube videos). I believe if some one gives us a solution I can also pay them. (Please don't remove my comment)

**Comment by greg-schroeder** [comment]
Hi ... sorry, I think I made a mistake and I already paid @akinwale based on [this issue](https://github.com/Expensify/App/issues/37921). However, based on the [comment here](https://github.com/Expensify/App/issues/37921#issuecomment-2017609639) it seems there's also an offer here, and it might not even be paid in the first place?

Anyone have thoughts on what I should do? Sorry for the trouble here
