### ISSUE TITLE
[$500] Investigate crash Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#36428]
In 1.4.40 version of the app, we could observe following crash Android OS version: android11 Model:OnePlus8Pro :

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.expensify.chat/com.expensify.chat.MainActivity}: java.lang.reflect.InvocationTargetException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3433)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Full stack trace is [here](https://github.com/Expensify/App/files/14270573/com.expensify.chat_issue_d38762c051e8ef3bfe9d2191f3597886_crash_session_65CB6624002400013B26F76E693B000E_DNE_0_v2_stacktrace.txt)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8073862ff8a28b6</li>
        <li>Upwork Job ID: 1757467639089561600</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Uh oh haha, who created that dupe 🌫️
