### ISSUE TITLE
[$250] [HOLD for payment 2024-06-05] Investigate android com.facebook.jni.CppException crash

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#40699]
There seems to be crash occurring on some android devices coming from reanimated, anyone able to investigate? 
<img width="1085" alt="image" src="https://github.com/Expensify/App/assets/36083550/9c2c5e6b-fe6e-4a64-bd4a-0624ac7dc0f9">

```
Fatal Exception: com.facebook.jni.CppException: [Reanimated] Data type not recognized by value unpacker.

Error: [Reanimated] Data type not recognized by value unpacker.
    at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)
       at com.swmansion.reanimated.AndroidUIScheduler.triggerUI(AndroidUIScheduler.java)
       at com.swmansion.reanimated.AndroidUIScheduler$1.run(AndroidUIScheduler.java:24)
       at com.swmansion.reanimated.AndroidUIScheduler$2.runGuarded(AndroidUIScheduler.java:43)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01666daee472e0a157</li>
        <li>Upwork Job ID: 1797627295389204480</li>
        <li>Last Price Increase: 2024-06-03</li>
    </ul>
</details>

**Comment by saifelance** [comment]
@tienifr 
crashes related to android com.facebook.jni.CppException. The root cause appears to stem from a known issue, as reported. To address it, upgrading the library to the latest version seems like a viable solution.

**Comment by mountiny** [comment]
@tienifr feel free to go ahead to prepare the bump PR

**Comment by mountiny** [comment]
Ooof, sorry for that, I think I could make you a C+ here if you want, seems like you know how to replicate this, would you live to do a C+ work here on the PR?

**Comment by mountiny** [comment]
Gonna do that than, @tienifr please notify the C+ that will get autoassigned to the PR review

**Comment by joekaufmanexpensify** [comment]
@tienifr is there an ETA for the PR here?

**Comment by joekaufmanexpensify** [comment]
@tienifr is the testing issue resolved?

**Comment by joekaufmanexpensify** [comment]
Awesome. TY! PR still in review

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
I don't think BZ checklist is needed here.

**Comment by joekaufmanexpensify** [comment]
Payment needed here is: 

- @tienifr - $250 for PR via upwork. 
- @ShridharGoel - $250 for C+ via upwork

**Comment by joekaufmanexpensify** [comment]
offers sent to both of you!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
