### ISSUE TITLE
[$250] Attachment - The app crashes when attempting to open larger specific pdf

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40925]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**(https://expensify.testrail.io/index.php?/tests/view/4510570&group_by=cases:section_id&group_order=asc&group_id=292107)
**Email or phone of affected tester (no customers):** shussain+accoun1@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. On a conversation, click on the + button in the compose box
2. Upload attached larger pdf to a conversation
3. Then click on it to preview

## Expected Result:
Attachment should be displayed in preview

## Actual Result:
The app crashes when attempting to open larger specific pdf

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5ca52a0c-145c-4ac7-9c1e-f61620d9593a

[Bug6460367_1713968986208!class-9-maths-chapter-10-solutions-2024-02-08_22_17_00.194.pdf](https://github.com/Expensify/App/files/15098281/Bug6460367_1713968986208.class-9-maths-chapter-10-solutions-2024-02-08_22_17_00.194.pdf)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efa7ba36a86bb510</li>
        <li>Upwork Job ID: 1783189054673006592</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by mountiny** [comment]
I dont see anything specific in the checklist that could influence PDF updates

**Comment by mountiny** [comment]
It seems like its related to this crash logs

```
Fatal Exception: com.facebook.jni.CppException: JSON Parse error: Unexpected end of input

SyntaxError: JSON Parse error: Unexpected end of input
    at parse (native)
       at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(EventHandler.java)
       at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(EventHandler.java:25)
       at com.facebook.react.uimanager.events.Event.dispatch(Event.java:167)
       at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:328)
       at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:314)
       at com.facebook.react.uimanager.events.FabricEventDispatcher.dispatchEvent(FabricEventDispatcher.java:42)
       at com.facebook.react.fabric.interop.InteropEventEmitter.receiveEvent(InteropEventEmitter.java:50)
       at org.wonday.pdf.PdfView.loadComplete(PdfView.java:151)
       at com.github.barteksc.pdfviewer.listener.Callbacks.callOnLoadComplete(Callbacks.java:83)
       at com.github.barteksc.pdfviewer.PDFView.loadComplete(PDFView.java:830)
       at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:90)
       at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:27)
       at android.os.AsyncTask.finish(AsyncTask.java:755)
       at android.os.AsyncTask.access$900(AsyncTask.java:192)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7684)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by Engr-Shoaib** [comment]
I think issue are in these files.
AttachmentView.
![Screenshot_20240425-020346](https://github.com/Expensify/App/assets/144941171/c5858282-2ed3-474d-9be6-a80cc5194a3e)

**Comment by Engr-Shoaib** [comment]
Contributor details
Your Expensify account email: engrshoaibh@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a43dc9bc6efe1518

I think issue are in these files.
![Screenshot_20240425-020346](https://github.com/Expensify/App/assets/144941171/0c506699-063d-473b-b4f8-0895a7641c64)

**Comment by mountiny** [comment]
I have tested uploading some pdf files and did not encounter the crash. I have informed SWM to look into the crash tomorrow, I think we can demote as there are no clear reproduction steps, seems like it might be specific to device or the file

**Comment by Engr-Shoaib** [comment]
Yes I also try this feature but it's work properly.

**Comment by arosiclair** [comment]
No proposals for now. Doesn't seem like any of us have reproduced either.
