### ISSUE TITLE
[Crashlytics] ResourceOptionsManager$Companion.getDefault

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#45055]
Device
Brand:Samsung
Model:Galaxy A35 5G
Orientation:Portrait
RAM free: 1.89 GB
Disk free: 91.45 GB
Operating System
Version:Android 14
Orientation:Portrait
Rooted:No
Crash
Date:Jul 9, 2024, 9:21:33 AM
App version:9.0.3-7 (1009000307)

com.mapbox.maps
ResourceOptionsManager.kt:71

[com.expensify.chat_issue_963cc500441d92b84a05a8c3ee5b3f2d_crash_session_668CF2F6015B0001125C8FC96F517223_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16141769/com.expensify.chat_issue_963cc500441d92b84a05a8c3ee5b3f2d_crash_session_668CF2F6015B0001125C8FC96F517223_DNE_0_v2_stacktrace.txt)

```
com.mapbox.maps.MapboxConfigurationException - Using MapView requires providing a valid access token when inflating or creating the view. Provide the token by either: 1. Initialising the MapView programmatically using 'MapInitOptions' and configure the token using 'MapInitOptions.resourceOptions.acce
```

```
          Fatal Exception: com.mapbox.maps.MapboxConfigurationException: Using MapView requires providing a valid access token when inflating or creating the view.
Provide the token by either:
  1. Initialising the MapView programmatically using 'MapInitOptions' and configure the token using 'MapInitOptions.resourceOptions.accessToken'.
  2. Or by passing it using MapView's 'mapbox_resourcesAccessToken' XML attribute.
  3. Or by creating a mapbox_access_token string resource.
The access token parameter is required when using a Mapbox service.
Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
       at com.mapbox.maps.ResourceOptionsManager$Companion.getDefault(ResourceOptionsManager.kt:71)
       at com.mapbox.maps.ResourceOptionsManager$Companion.getDefault$default(ResourceOptionsManager.kt:50)
       at com.mapbox.maps.MapInitOptions$Companion.getDefaultResourceOptions(MapInitOptions.kt:47)
       at com.mapbox.maps.MapInitOptions.<init>(MapInitOptions.kt:28)
       at com.mapbox.maps.MapView.<init>(MapView.kt:57)
       at com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.createMapView(RNMBXMapView.kt:1168)
       at com.rnmapbox.rnmbx.components.mapview.RNMBXMapView.applyAllChanges(RNMBXMapView.kt:617)
       at com.rnmapbox.rnmbx.components.mapview.RNMBXMapViewManager.onAfterUpdateTransaction(RNMBXMapViewManager.kt:82)
       at com.rnmapbox.rnmbx.components.mapview.RNMBXMapViewManager.setCompassImage(RNMBXMapViewManager.kt:53)
       at com.rnmapbox.rnmbx.components.mapview.RNMBXMapViewManager.onAfterUpdateTransaction(RNMBXMapViewManager.kt:53)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:81)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:181)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:108)
       at com.facebook.react.views.view.ReactViewManagerWrapper$DefaultViewManager.createView(ReactViewManagerWrapper.kt:59)
       at com.facebook.react.fabric.mounting.SurfaceMountingManager.createViewUnsafe(SurfaceMountingManager.java:860)
       at com.facebook.react.fabric.mounting.SurfaceMountingManager.preallocateView(SurfaceMountingManager.java:1230)
       at com.facebook.react.fabric.mounting.mountitems.PreAllocateViewMountItem.execute(PreAllocateViewMountItem.java:64)
       at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:359)
       at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchPreMountItems(MountItemDispatcher.java:338)
       at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1302)
       at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:30)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
       at android.view.Choreographer.doFrame(Choreographer.java:1069)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by TMisiukiewicz** [comment]
this one should be fixed once #44767 is deployes

**Comment by johncschuster** [comment]
The linked PR has been deployed to staging. Waiting on a deploy to prod.

**Comment by johncschuster** [comment]
Payment Summary:

Contributor: @TMisiukiewicz - does not require payment

Contributor+: @shubham1206agra owed $250 via Upwork (I will issue payment in two days)

**Comment by johncschuster** [comment]
Thanks, @shubham1206agra! In that case, it sounds like we can close this one out. Please let me know if I've missed something!
