### ISSUE TITLE
[HOLD for payment 2024-08-29]  [Crashlytics] TypeError: right operand of 'in' is not an object - ReportIDsContextProvider

### ISSUE THREAD

**Issue by CortneyOfstad** [Expensify/App#46115]
Coming from this GH — https://github.com/Expensify/App/issues/45054#issuecomment-2238548276

Reported by @TMisiukiewicz 

Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: right operand of 'in' is not an object

```
This error is located at:
    in ReportIDsContextProvider
    in ActiveWorkspaceContextProvider
    in ActiveElementRoleProvider
    in CustomStatusBarAndBackgroundContextProvider
    in EnvironmentProvider
    in PickerStateProvider
    in ReportAttachmentsProvider
    in ScrollOffsetContextProvider
    in withOnyx(ScrollOffsetContextProvider)
    in Unknown
    in CurrentReportIDContextProvider
    in PopoverContextProvider
    in KeyboardStateProvider
    in WindowDimensionsProvider
    in RenderersPropsProvider
    in ListStyleSpecsProvider
    in SharedPropsProvider
    in RenderRegistryProvider
    in RenderHTMLConfigProvider
    in TRenderEngineProvider
    in BaseHTMLEngineProvider
    in HTMLEngineProvider
    in LocaleContextProvider
    in withOnyx(LocaleContextProvider)
    in Unknown
    in WithCurrentUserPersonalDetails(Component)
    in _default
    in PortalProviderComponent
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in ThemeIllustrationsProvider
    in ThemeStylesProvider
    in ThemeProvider
    in AccountProvider
    in withOnyx(AccountProvider)
    in Unknown
    in SessionProvider
    in withOnyx(SessionProvider)
    in Unknown
    in Nvp_expensify_preferredEmojiSkinToneProvider
    in withOnyx(Nvp_expensify_preferredEmojiSkinToneProvider)
    in Unknown
    in Nvp_expensify_frequentlyUsedEmojisProvider
    in withOnyx(Nvp_expensify_frequentlyUsedEmojisProvider)
    in Unknown
    in PreferredThemeProvider
    in withOnyx(PreferredThemeProvider)
    in Unknown
    in ReportDraftComment_Provider
    in withOnyx(ReportDraftComment_Provider)
    in Unknown
    in BetasProvider
    in withOnyx(BetasProvider)
    in Unknown
    in Nvp_private_blockedFromConciergeProvider
    in withOnyx(Nvp_private_blockedFromConciergeProvider)
    in Unknown
    in CurrentDateProvider
    in withOnyx(CurrentDateProvider)
    in Unknown
    in ReportActionsDrafts_Provider
    in withOnyx(ReportActionsDrafts_Provider)
    in Unknown
    in PersonalDetai<truncated: 1021 chars>
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
       at java.lang.Thread.run(Thread.java:1012)
```

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by roryabraham** [comment]
these logs are truncated so we can't see where the actual error is happening: https://expensify.slack.com/archives/C05LX9D6E07/p1722277152549049

**Comment by TMisiukiewicz** [comment]
@roryabraham @CortneyOfstad I'm gonna take a look if it's possible

**Comment by TMisiukiewicz** [comment]
can we change it to weekly?

**Comment by CortneyOfstad** [comment]
@TMisiukiewicz sorry for the delay here — I was OoO, but adjusting the frequency now!

**Comment by c3024** [comment]
@marcochavezf 

Can you please assign me to this issue as I reviewed the PR?

**Comment by CortneyOfstad** [comment]
No check list is required, and just confirming with the team on the payment for this. Thanks for your patience @c3024!

**Comment by c3024** [comment]
@CortneyOfstad, accepted the offer. Thanks!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@TMisiukiewicz — not paid as a vendor
@c3024 — paid $250 via Upwork

Thanks all!
