### ISSUE TITLE
[Crashlytics] TypeError: undefined is not a function

### ISSUE THREAD

**Issue by CortneyOfstad** [Expensify/App#46117]
Coming from this GH — https://github.com/Expensify/App/issues/45054#issuecomment-2238548276

Reported by @TMisiukiewicz 

```
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: undefined is not a function, js engine: hermes, stack:
init@1:2323334
_default@1:7673375
anonymous@1:180908
loadModuleImplementation@1:170989
guardedLoadModule@1:170179
metroRequire@1:169506
global@1:168441

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by CortneyOfstad** [comment]
@TMisiukiewicz it was indicated on one of the other Crashlytic GHs that the logs are truncated. Any way you could pull up the full logs? Thanks!

**Comment by TMisiukiewicz** [comment]
can we change it to weekly?

**Comment by CortneyOfstad** [comment]
Sorry, was OoO, so adjusting the frequency now!

**Comment by CortneyOfstad** [comment]
Thanks for the detailed explanation @hurali97!

@TMisiukiewicz reviewing the comment above, there may potentially be an issue in the breadcrumb flow from the original issue that this was created from. Do you have any insight into what could potentially be missing or needs to be adjusted in order to recreate?

**Comment by TMisiukiewicz** [comment]
@CortneyOfstad currently breadcrumbs are tied only to navigation events only, and this, unfortunately, it gaves us very limited knowledge about users actions. When I have a bit more capacity, I am planning to review if there is a space for improvements in this area.

Also, the proposal from @hurali97 looks good to me 👍

**Comment by hurali97** [comment]
@CortneyOfstad do you think we can move forward with creating a PR to fix this?

**Comment by CortneyOfstad** [comment]
Sorry for the delay here — PR looks great! Thank you!

**Comment by CortneyOfstad** [comment]
@paultsimura proposed solution is [here](https://github.com/Expensify/App/issues/46117#issuecomment-2301587995)

**Comment by francoisl** [comment]
The explanation makes sense, but since the `url` param is already defined as a string in the TS function signature `getExtension(url: string)`, wouldn't adding a check on `typeof url` be redundant?

**Comment by hurali97** [comment]
> The explanation makes sense, but since the `url` param is already defined as a string in the TS function signature `getExtension(url: string)`, wouldn't adding a check on `typeof url` be redundant?

@francoisl That's true but it will only take effect in debug builds. On release builds, TS is stripped and we only have plain JS, so there could be anything passed to `getExtension`. Since we are not aware of the reproduction steps, we can't test this locally and see what value is being passed to it and why.

Since `typeof` is a JS operator it will be present in the final JS build and guarantees that the no type other than `string` should fall through.

**Comment by hurali97** [comment]
> The explanation and the solution in the [proposal](https://github.com/Expensify/App/issues/46117#issuecomment-2301587995) look good to me.
> 
> **🎀👀🎀 C+ reviewed**
> 
> I'm a little uncertain about the testing method for this issue though – do we just create a PR inside `expensify-common` and add unit tests to cover the failure scenarios? Or are there specific steps to reproduce the original error?

@paultsimura  unfortunately, we don't have any reproduction steps. I agree that to give us more confidence we can add unit tests.

I will create a PR shortly and add unit tests for the implementation.

**Comment by iwiznia** [comment]
I got the PR to review and have the same concern as @francoisl. This should not be needed and should be caught by TS.

I see you say we don't have reproduction steps, but we do have some trace, can't we use that to figure out where this is coming from and why it is not being caught by TS?

**Comment by hurali97** [comment]
> I got the PR to review and have the same concern as @francoisl. This should not be needed and should be caught by TS.
> 
> I see you say we don't have reproduction steps, but we do have some trace, can't we use that to figure out where this is coming from and why it is not being caught by TS?

@iwiznia I agree and I provided an explanation [here](https://github.com/Expensify/App/issues/46117#issuecomment-2323991112). TS will only help us in debug environments, so it won't catch anything on release.

As for the trace, they don't appear to be useful in order to further narrow down this issue. Only thing I was able to deduce was that we have calls to `isImage` and `isPDF`, which internally calls `getExtension`. The former functions are invoked in `getThumbnailAndImageURIs` and `MoneyRequestConfirmationListFooter` respectively and they deduce the fileName from `transaction` object.

I expect `transaction` object to come from Onyx and it could be a reason of stale onyx data or some other thing. I can not dive further on how it is possible to receive anything other than the string or undefined here, because of lack of reproduction data.

We can argue that we can add additional checks in these two places instead of adding one in `getExtension` but it won't scale. If in future, we have crashes in other places we will need to add checks in those places as well.

**Comment by iwiznia** [comment]
> TS will only help us in debug environments, so it won't catch anything on release.

The whole idea of TS is that it provides "compile" time checks. Why is it not catching this bad call then?

I'd be much more on board if we:
- Deployed a change that would log when the bad call is made (and avoid crashing)
- Wait for the line to get logged 
- Figure out why TS was not catching it as it should and fix that
- Revert the PR in step 1
- Close this issue

**Comment by hurali97** [comment]
@iwiznia Since you're already saying that "TS provides compile time checks", so it won't help us in runtime which means you can pass any data to it.

>Why is it not catching this bad call then?

Because in compile time, we are not invoking `getExtension` with bad data.

If you want, we can add a log of what data are we passing to `getExtension`, only in the case if it's type is not `string | undefined`. Also, if we go down this path, I think it won't be okay to add a firebase bread crumb from this function, so as to keep it decoupled. So this would mean to add a log wherever, `getExtension` is called from `isPDF` and `isImage`, that's a total of 19 places in the App codebase, so a lot of redundancy.

Anyways, Let me know what you think of the above.

<hr/>

From my experience, most of the open-source libraries use additional runtime checks in order to ensure safety, where there's a chance of type ambiguity or a union type. Also, I think the cost of doing above is more than adding a runtime check.

**Comment by iwiznia** [comment]
> Because in compile time, we are not invoking getExtension with bad data.

I am confused, nothing is really invoked at compile time.

@francoisl curious for your thoughts about the PR...

**Comment by iwiznia** [comment]
> However, there are cases when the passed parameter's type is not clearly known (e.g. it comes from some file parsing library). We assume it's a string, and we pass it as such into the function, and the TS compiler doesn't complain.

But even in this case, wherever that parsing call is done the variables should be typed and thus should still get the error, no?
If everything is ts and has proper types, the bug should be caught by ts somewhere.

**Comment by francoisl** [comment]
Left a comment in the PR about the logs, but for now I'm not sure I understand the part about the firebase breadcrumb in this comment:

> If you want, we can add a log of what data are we passing to getExtension, only in the case if it's type is not string | undefined. Also, if we go down this path, I think it won't be okay to add a firebase bread crumb from this function, so as to keep it decoupled. So this would mean to add a log wherever, getExtension is called from isPDF and isImage, that's a total of 19 places in the App codebase, so a lot of redundancy.

Would it be fine if we use `Log.alert()` with `includeStackTrace: true` directly in str.js? That way it's just one place to update, and we'd still get a stacktrace to get context about where the issue was from?

**Comment by francoisl** [comment]
Oh, we still need a PR to bump the expensify-common version in `package.json`, @hurali97 do you mind sending one please?

**Comment by deetergp** [comment]
We are about to bump to `2.0.88` in this [PR](https://github.com/Expensify/App/pull/49038). Do you want us to wait, or just pull in your changes with ours?

**Comment by francoisl** [comment]
Still waiting on https://github.com/Expensify/App/pull/49038 to be merged

**Comment by francoisl** [comment]
Ah nice, and it was just deployed to production too.

I think we can issue payments and close this. With the new `Log.warn`, if the issue shows up again, we'll see it in our logs and an internal engineer will be assigned to investigate.

**Comment by CortneyOfstad** [comment]
@paultsimura — i sent you an offer in Upwork [here](https://www.upwork.com/jobs/~021843643877682715478). Please let me know once you accept, and I'll get that paid ASAP. Thanks!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@paultsimura — paid $250 via Upwork
@hurali97 — contracted position (CallStack)
