### ISSUE TITLE
[Crashlytics] TypeError: right operand of 'in' is not an object - isResolvedActionTrackExpense

### ISSUE THREAD

**Issue by CortneyOfstad** [Expensify/App#46116]
Coming from this GH — https://github.com/Expensify/App/issues/45054#issuecomment-2238548276

Reported by @TMisiukiewicz 

```
 Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: right operand of 'in' is not an object, js engine: hermes, stack:
isResolvedActionTrackExpense@1:3076372
shouldReportActionBeVisibleAsLastAction@1:3076573
anonymous@1:3077049
getLastVisibleAction@1:3077001
getLastVisibleMessage@1:2541502
isEmptyReport@1:2573711
isUnread@1:2573782
anonymous@1:3471986
getUnreadReportsForUnreadIndicator@1:3471963
memoized@1:2151663
anonymous@1:3472312
invokeFunc@1:2514740
trailingEdge@1:2515070
timerExpired@1:2515019
anonymous@1:499374
_callTimer@1:498645
callTimers@1:500433
__callFunction@1:199931
anonymous@1:197417
__guard@1:199287
callFunctionReturnFlushedQueue@1:197375

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by CortneyOfstad** [comment]
@TMisiukiewicz it was indicated on one of the other Crashlytic GHs that the logs are truncated. Any way you could pull up the full logs? Thanks!

**Comment by TMisiukiewicz** [comment]
I think this one was resolved in https://github.com/Expensify/App/pull/45580 - no crashes were reported after publishing 9.0.8 version

**Comment by TMisiukiewicz** [comment]
can we change it to weekly?

**Comment by CortneyOfstad** [comment]
Sorry for the delay in regards to [this comment](https://github.com/Expensify/App/issues/46116#issuecomment-2268593719) — I was OoO, so closing this now! Thanks!
