### ISSUE TITLE
Android - Expense - App crashes when uploading a PDF receipt after uploading a photo receipt

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49349]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+watashiwastar2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Submit expense > Manual.
3. Enter amount and select a user.
4. On confirmation page, tap 3-dot menu > Add receipt.
5. Add any photo receipt from device gallery.
6. On confirmation page with the photo receipt, tap 3-dot menu > Add receipt.
7. Select Choose file.
8. Select the PDF file (attached below) (happens with this PDF file only).
9. Might need to repeat Step 4 to 8 to reproduce the crash.

## Expected Result:
App will not crash.

## Actual Result:
App crashes when uploading a PDF receipt after uploading a photo receipt.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[1709.txt](https://github.com/user-attachments/files/17033352/1709.txt)

https://github.com/user-attachments/assets/ff631842-5a15-4ec0-ab5d-cc4bf486a8f8

[Bug6606744_1726588963019!International_Money_Transfer__Send_Money_Abroad_with_Wise__ex-TransferWise_.pdf](https://github.com/user-attachments/files/17033357/Bug6606744_1726588963019.International_Money_Transfer__Send_Money_Abroad_with_Wise__ex-TransferWise_.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment]
ongoing slack convos:
open-source: https://expensify.slack.com/archives/C02NK2DQWUX/p1726598780128409
deployer: https://expensify.slack.com/archives/C07J32337/p1726599054838339?thread_ts=1726595505.237429&cid=C07J32337

**Comment by mountiny** [comment]
Reopening to handle this update and fix the issue

**Comment by mountiny** [comment]
[com.expensify.chat_issue_85c581edcdb39b941df627e7b1324a71_crash_session_66e8e6b7001c00016a8be1d135199580_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17034170/com.expensify.chat_issue_85c581edcdb39b941df627e7b1324a71_crash_session_66e8e6b7001c00016a8be1d135199580_DNE_0_v2_stacktrace.txt)

```
--------- beginning of crash
09-17 23:58:21.532  8197  8703 E AndroidRuntime: FATAL EXCEPTION: PDF renderer
09-17 23:58:21.532  8197  8703 E AndroidRuntime: Process: com.expensify.chat, PID: 8197
09-17 23:58:21.532  8197  8703 E AndroidRuntime: java.lang.IllegalStateException: Already closed
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at io.legere.pdfiumandroid.util.ConfigKt.handleAlreadyClosed(SourceFile:44)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at io.legere.pdfiumandroid.PdfPage.close(SourceFile:18)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at S5.J3.a(SourceFile:5)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at io.legere.pdfiumandroid.PdfiumCore.renderPageBitmap(SourceFile:6)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at x3.k.b(SourceFile:189)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at x3.k.handleMessage(SourceFile:7)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
09-17 23:58:21.532  8197  8703 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-17 23:58:21.534  8197  8197 D jniPdfium: Destroy FPDF library
09-17 23:58:21.568  1912  1912 I Layer   : Layer [Sprite#2978] hidden!! flag(1)
09-17 23:58:21.569  2632  4778 I NSLocationMonitor: getGPSUsingApps() called
09-17 23:58:21.571  4757 15254 I NSLocationManager_FLP: getGPSUsingApps, NO_FREEZE={5013} / FREEZE={10235}
09-17 23:58:21.573  1912  1912 D SurfaceFlinger: Display 4630946213010294403 HWC layers:
```

**Comment by mountiny** [comment]
Some logs from the crash

**Comment by mountiny** [comment]
Asked SWM to look into [this](https://expensify.slack.com/archives/C04878MDF34/p1726602298067909)

**Comment by mountiny** [comment]
@j-piasecki @blazejkustra Who is working on this one? Can they please comment so I can assign them? thanks!

**Comment by j-piasecki** [comment]
I believe @Guccio163 is currently investigating this.

**Comment by Guccio163** [comment]
That's right, I'm Wiktor Gut from SWM, please assign me this issue

**Comment by Guccio163** [comment]
Hi, I'm just letting you know that it can take a little more time, I've reproduced this bug on current main; It can be not a package, but implementation problem - there are also similar bugs reported [here](https://github.com/wonday/react-native-pdf/issues/868) encountered when updating RN from 0.71 to 0.74.5

**Comment by mountiny** [comment]
Interesting, we were not able to reproduce with many tries after revert

Thanks for the update

**Comment by Guccio163** [comment]
I understand, it is really non-deterministic - sometimes it goes after 4th try and sometimes doesn't break after 20th, this is the main reason why it takes time because is hard to test 🐢

**Comment by Guccio163** [comment]
Hi 👋 , I'm dropping by to let you know how the investigation is going; Fortunately problem proved to be linked to the reverted PR (version 6.7.5 of react-native-pdf library) and doesn't occur on current main - it turned out to be a local problem of android studio on my laptop (solved today). Unfortunately, there are numerous issues linked to the 6.7.5 version crash (f.ex. https://github.com/wonday/react-native-pdf/issues/830 and https://github.com/wonday/react-native-pdf/issues/833). Some are left untouched and some contain solutions which doesn't work in our case. I'll keep investigating further with @j-piasecki  's help, we'll do out best to find the best suiting solution 🔜

**Comment by andrewhamili** [comment]
![image](https://github.com/user-attachments/assets/5162c3c3-ffb0-460a-bf6d-0e99bf397d51)
+1

**Comment by Guccio163** [comment]
Hi 👋, I'm coming with some sort of conclusion, though not the perfect ending which we searched for; The problem itself lies somewhere inside the new version of the library. 

## Logs analysis and search: ##
Bug is inconsistent both in occurrence and causes what makes debugging noticeably harder; inconsistent occurrence was mentioned earlier and when it comes to causes, logs show one of 3 causes for crash: 
- `Parameter specified as non-null is null`
- `Already closed`
- `Already opened`

Moreover logs produced by pdf library (blue ones) doesn't show anything unusual in terms of opening/closing documents, below comparison of logs without crash and resulting in crash. Both situations are chains `close document`->`destroy library`->`draw pdf`->`init library`->`close document`->`destroy library`:

- Working properly:
<img width="1102" alt="Screenshot 2024-09-26 at 13 56 16" src="https://github.com/user-attachments/assets/039bbc84-f886-482f-bb07-04420b26fb9b">

- Resulting in `Already closed` crash:
<img width="1147" alt="Screenshot 2024-09-26 at 13 57 42" src="https://github.com/user-attachments/assets/fed4e514-73fc-4bcf-b27e-7499e58c9606">

## Library problem: ##
Incorrect behaviour of the app is caused by the `6.7.5` version of the library itself reported in numerous issues (also caused whole app crash), some of them mentioned in previous comments; most of working solutions are based on going back to previous versions of the library. Moreover the `react-native-pdf` itself added native android library `pdfiumandroid` rewritten in Kotlin, which may be extra occasion for implementation errors (was previously in Java).

## Purpose of reverted PR: ##
The whole purpose of @WoLewicki 's PR which was reverted to prevent this crash was to bump the library from `6.7.3` to `6.7.5`, because `6.7.5` had merged a patch which was needed in `6.7.3`; This way we could have just a newer version of the library without extra add-ons. Taking into consideration that `6.7.5` has unforeseen bugs, it would be meaningless to bump the library to newer version just to be forced to write new patches.

## Solution: ##
Leave the PR reverted and keep the `6.7.3` version. It works great and without bugs as we already have them fixed, when the `6.7.5` would cause more of them.

cc @mountiny, WDYT?

**Comment by mountiny** [comment]
discussed in Slack [here](https://expensify.slack.com/archives/C04878MDF34/p1727363703744479) and we agreed that it's not worth spending more time here and we do not need to bump the library so until we would really need to use something from the newer version, we can pass

**Comment by roryabraham** [comment]
Rather than closing this outright, can we reopen it, make it a monthly, and put it on HOLD for the upstream issue?

That way this investigation isn't forgotten and we can upgrade the lib when the upstream issues are fixed (i.e: to remove patches and keep it up-to-date in case of security vulnerabilities and such)

**Comment by greg-schroeder** [comment]
I think we should actually close this, though, now that #vip-vsb is paused/closed/archived though, yes? That seems to be the conclusion per https://expensify.slack.com/archives/C03U7DCU4/p1727723600645479

Lemme know if you disagree or you think this could fit in a different project @roryabraham!

**Comment by mountiny** [comment]
Adding this to the newdot quality project and keeping it open so we can follow up in future once upstream is fixed @greg-schroeder feel free to unassign as there is nothing to do for you now

**Comment by mountiny** [comment]
waiting

**Comment by mountiny** [comment]
@Guccio163 Can you please check if this was resolved upstream? Could we clear this up with an update?

**Comment by Guccio163** [comment]
I will look into it in the next week 👌

**Comment by mountiny** [comment]
@Guccio163 any updates?

**Comment by Guccio163** [comment]
Hi 👋 , I haven't still got a while to investigate this, I'm working hard over finishing [share-extension PR](https://github.com/Expensify/App/pull/54354); If it's okay with you I'll start working over this as soon as I'll be finished with the share-extension one

**Comment by Guccio163** [comment]
Hi @mountiny, I'm coming back with an update after a dive into this new release: There is no straightforward information about this release fixing `java.lang.IllegalStateException: Already closed` bug that occurred here and I didn't find any of the similar bug reports that would have a note that it has been resoled by this patch.

I've tried to reproduce this bug by adding the pdf 20 times, 3 separate times, totally 60 attempts to induce it and I couldn't. There is a chance it got resolved, because one of the patch's commits handles `java.lang.IllegalStateException` bug, but not exactly ours; we can't be sure though, because it hasn't been mentioned anywhere. @IuliiaHerets maybe You could take a peek at it and let us know if it is reproducible?

**Comment by mountiny** [comment]
I will ask

**Comment by mountiny** [comment]
https://expensify.slack.com/archives/C9YU7BX5M/p1737576349693079

**Comment by mountiny** [comment]
They confirmed this is not repro anymore, so I think we can close! @Guccio163 Thanks for looking!
