### ISSUE TITLE
[HybridApp] Android - Crash when creating GPS expense

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#50070]
### Problem

We have a [new crash ](https://console.firebase.google.com/project/expensify-mobile-app/crashlytics/app/android:org.me.mobiexpensifyg/issues/ed7a1e85d12b74eab47956ad5c788ffe?versions=9.0.39.5%20(509003905)&time=last-thirty-days&types=crash&sessionEventKey=66FD5F4403C300015774A583F5BF6EA5_1999638117596131718)occuring our most recent HybridApp production build.

This seems to be easily resolvable, by categorising the Foreground service that is likely triggered by our location request...

```
 Caused by android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{a8be428 22388:org.me.mobiexpensifyg/u0a390} targetSDK=34
       at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
       at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
       at android.os.Parcel.readParcelable(Parcel.java:4864)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
       at android.os.Parcel.createException(Parcel.java:3053)
       at android.os.Parcel.readException(Parcel.java:3036)
       at android.os.Parcel.readException(Parcel.java:2978)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7248)
       at android.app.Service.startForeground(Service.java:775)
       at yapl.android.location.LocationRequestService.showNotification(LocationRequestService.java:82)
       at yapl.android.location.LocationRequestService.onStartCommand(LocationRequestService.java:33)
```

### Solution

For now, monitor as we continue to rollout. But we should plan to ship this fix as a follow up release.

**Comment by Julesssss** [comment]
Becoming a problem. I'm halting the Android rollout temporarily at 20% to investigate further. Our current crash rate is 3% of users, and 4.7% of sessions 😬 

<img width="407" alt="Screenshot 2024-10-03 at 09 29 45" src="https://github.com/user-attachments/assets/fd7cb569-5be8-4df3-b5bc-9c763ca2d2ba">

**Comment by Julesssss** [comment]
I can reproduce by starting a GPS distance request in OldDot. We're not setting a foreground service type, which is a new [requirement](https://developer.android.com/about/versions/14/changes/fgs-types-required) as of Android 14.

Not sure how this was missed during our QA smoke testing...  I created an issue [here ](https://github.com/Expensify/Expensify/issues/433034)to ensure we get this case added.

**Comment by Julesssss** [comment]
Hold for a moment. I need an additional AndroidManifest change

**Comment by Julesssss** [comment]
PR in review, confirmed fixed.
