### ISSUE TITLE
Tour link - Tour link does not disappear after it is clicked for Expensifail accounts

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+sjdosjdsod@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with Expensifail account.
3. Click FAB.
4. Open tour link.
5. Complete the tour.
6. Go back to ND.
7. Open FAB.

## Expected Result:
Tour link should disappear after it is clicked.

## Actual Result:
Tour link does not disappear after it is clicked for Expensifail accounts.

This issue is not reproducible with Gmail accounts.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/aa14f26a-f4a5-4064-b59b-d8a86688fade
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
Commented on offending PR

**Comment by MonilBhavsar** [comment]
I think we can most probably demote from blocker as it's a new feature, but curious to hear PR author's thoughts

**Comment by MonilBhavsar** [comment]
expensifail is just a private domain. Did you try using a private domain?

This is something that stands out in the log.
```
[App] 2024-11-06T00:15:33.569Z - [alXt] [Onyx] Warning: Trying to apply "merge" with non-array type to array type in the key "nvp_onboarding" ~~ stack: '"Error\n at t.default.alert (https://staging.new.expensify.com/vendors-24902c76fb140ef2f7f3.bundle.js:2:2696325)\n at https://staging.new.expensify.com/main-3013b01992919466ef5e.bundle.js:1:191919\n at t.logAlert (https://staging.new.expensify.com/vendors-24902c76fb140ef2f7f3.bundle.js:2:3403296)\n at https://staging.new.expensify.com/vendors-24902c76fb140ef2f7f3.bundle.js:2:3406084\n at Array.filter (<anonymous>)\n at https://staging.new.expensify.com/vendors-24902c76fb140ef2f7f3.bundle.js:2:3405952\n at async Promise.all (index 0)"' userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
```
Source https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228de0e3d5a804d42e-KUL%22)+AND+timestamp:[2024-11-05T23:15:35.425Z+TO+2024-11-06T01:15:35.425Z]&index=logs_expensify-031069

**Comment by c3024** [comment]
For private domain accounts with domain control setup, one cannot login without a magic code. These accounts are treated as onboarding flow completed accounts. For such accounts, `OpenApp` returns an empty onboarding array `[]`. 

<img width="346" alt="Screenshot 2024-11-06 at 3 03 26 PM" src="https://github.com/user-attachments/assets/b684c80e-39e0-4094-89dd-a1695d404514">


No onboarding flow is shown. When we see the tour, we try to apply `MERGE` with an object to the array. Onyx complains 


<img width="541" alt="Screenshot 2024-11-06 at 3 04 34 PM" src="https://github.com/user-attachments/assets/daf72e18-9015-4fc9-a452-783c4d09d94e">



and does not update the `selfTourViewed` value. So, the `onboarding` remains as an empty array and the tour option keeps displayed.

I guess we need not show the tour link option for users who do not need to do the onboarding flow even though they login for the first time. Like private domain accounts in this case for which backend sends `onboarding` as `[]`.

@mountiny , can you please check this?

**Comment by MonilBhavsar** [comment]
Thanks for looking!
Explains the issue. 

I think we should display guided tours to users for first time, regardless of public or private domain.
It would be helpful to users to know about the app, especially in top-down flow.

I think this will be fixed if sever sends empty object instead of an array?

**Comment by c3024** [comment]
Yes, that should work. I am not sure how it works on backend but there seems to be some issue with php [converting](https://github.com/Expensify/App/pull/50493#issuecomment-2417136488) an empty object into an array.

**Comment by c3024** [comment]
I think we should also treat `selfTourViewed` as `true` here

https://github.com/Expensify/App/blob/573162fa38cb394a6d0a1c370ffc42279cecf493/src/libs/onboardingSelectors.ts#L47

for cases where `onboarding` is  sent as `[]` like we do here.

https://github.com/Expensify/App/blob/573162fa38cb394a6d0a1c370ffc42279cecf493/src/libs/onboardingSelectors.ts#L12-L15

https://github.com/Expensify/App/blob/573162fa38cb394a6d0a1c370ffc42279cecf493/src/libs/ReportUtils.ts#L8248

Otherwise, this same problem happens for such accounts because the `selfTourViewed` can never be updated to `true` because of the Onyx object -> array merge error.

**Comment by MonilBhavsar** [comment]
> Yes, that should work. I am not sure how it works on backend but there seems to be some issue with php https://github.com/Expensify/App/pull/50493#issuecomment-2417136488 an empty object into an array for sending empty objects.

Great 👍 Let's do it. 
It also makes this issue non blocker then

**Comment by MonilBhavsar** [comment]
Sent PR to fix this.

We might need an App followup for reason mentioned here https://github.com/Expensify/App/issues/52095#issuecomment-2459219847

**Comment by c3024** [comment]
@MonilBhavsar 

If we send `onboarding` as an empty object the onboarding flow gets displayed for domain control setup private domain accounts also because the `hasCompletedOnboardingFlow` will be `undefined` and this array check
https://github.com/Expensify/App/blob/573162fa38cb394a6d0a1c370ffc42279cecf493/src/libs/onboardingSelectors.ts#L12-L15
fails.

I think the object should have `hasCompletedOnboardingFlow` as `true` to retain the behaviour of not showing onboarding flow for private domain accounts.

**Comment by c3024** [comment]
Yes, that is the best solution IMO. 

Then the `selfTourViewed` nvp can be sent as `false` for new accounts from backend and it can be set/merged correctly after seeing the tour link. Merging the object with empty [] onboarding remains a problem otherwise.

**Comment by MonilBhavsar** [comment]
I think we should use onboarding NVP only since guided tour is a part of user onboarding

**Comment by mountiny** [comment]
Lets use the onboarding NVP.

@c3024 @rushatgabhane we can update that check to not having the `onboardingCompleted` property same as the array?

**Comment by MonilBhavsar** [comment]
> If we send onboarding as an empty object the onboarding flow gets displayed for domain control setup private domain accounts also because the hasCompletedOnboardingFlow will be undefined and this array check

@c3024 the object is only returned when onboarding NVP is empty. If we have any value it is returned as it is. I don't really understand this logic 

```
if (Array.isArray(onboarding)) { 
     return true; 
 } 
 ```
 
 May be we can replace it with actual logic i.e. if user is on domain controlled private domain return true

**Comment by MonilBhavsar** [comment]
Sounds good, thanks! 👍 
I think we should also check emptiness too

**Comment by mountiny** [comment]
working on this

**Comment by strepanier03** [comment]
@MonilBhavsar - Do @rushatgabhane and @c3024 require payment? They are assigned to the PR and I didn't want to close this if they were.

**Comment by c3024** [comment]
No, this **_was_** fixed with PR #52175. This is **_not_** reproducible anymore for domain workspace configured private domain accounts.

https://github.com/user-attachments/assets/50d8bf28-619d-4443-a006-33b5fea6c9d5

So, this should not be reproducible for Expensifail accounts as well.

**Comment by strepanier03** [comment]
So does that mean you're both owed $250 for https://github.com/Expensify/App/pull/52175?

**Comment by MonilBhavsar** [comment]
Vit made the PR. So, I think @c3024 only owes $250 for reviewing https://github.com/Expensify/App/pull/52175

**Comment by strepanier03** [comment]
Got it, thanks a bunch @MonilBhavsar - I'll spin that up now.

**Comment by strepanier03** [comment]
Okay, please reopen if the above is not correct.
