### ISSUE TITLE
Web - Workspace - Console error shows up when creating a new workspace

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#54152]
- HELD on https://github.com/Expensify/App/issues/38072

**Version Number:** 9.0.76-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** sdjsimdjosioidjso@mgial.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.0 / Chrome
**App Component:** Workspace Settings

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account (no workspace).
3. Open FAB. 
4. Click New workspace.

## Expected Result:
There will be no console error.

## Actual Result:
Console error shows up when creating a new workspace.

This issue only happens when creating the first workspace on accounts without workspace.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a8eb6a60-fddb-4df8-8e73-f125ad3ab3b3

[Bug6694138_1734166977907!staging.new.expensify.com-1734166801906.txt](https://github.com/user-attachments/files/18135582/Bug6694138_1734166977907.staging.new.expensify.com-1734166801906.txt)

![image (2)](https://github.com/user-attachments/assets/99de9561-3cad-4c9f-9714-c9d78c3c29b7)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @arosiclair</details>

**Comment by Christinadobrzyn** [comment]
I'm not getting an error - asking QA to retest - https://expensify.slack.com/archives/C9YU7BX5M/p1734369688951269

**Comment by kavimuru** [comment]
Tester is still able to reproduce.

https://github.com/user-attachments/assets/183d52f0-8b0d-4d2c-9f14-27755c5d41f0

**Comment by Christinadobrzyn** [comment]
Thanks @kavimuru! Ah it's only in the console... hum... I don't know how important that is to fix. Going to ask the team.

**Comment by Christinadobrzyn** [comment]
Asking Kavi for some more information about the console error based on the Slack chat with the team - https://expensify.slack.com/archives/C9YU7BX5M/p1734478832205519?thread_ts=1734369688.951269&cid=C9YU7BX5M

**Comment by Christinadobrzyn** [comment]
Screenshots of the error added in the OP. Following up with the team about this.

**Comment by Christinadobrzyn** [comment]
Reaching out to SWM to see if someone can investigate this.

**Comment by Christinadobrzyn** [comment]
Asking callstack https://expensify.slack.com/archives/C03UK30EA1Z/p1734722664657639

**Comment by arosiclair** [comment]
This is related to https://github.com/Expensify/Expensify/issues/424142. The error is coming from our third party GTM script [here](https://github.com/Expensify/App/blob/70b5c0c760b33007014654834bc5f6a619d0120e/web/thirdPartyScripts.js#L3-L12).  I didn't see this when we implemented initially but I'll try reproducing.

**Comment by arosiclair** [comment]
I reproduced in staging. There's a couple CSP errors we should address though I'm not sure if they're the root of this problem:

```
gtm.js?id=GTM-N4M3FLJZ:501 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-MDY2MDQ0MGQ3MD/MGQyMGEwMTIwZjAwMjYwYTIwZmQ='

...

Either the 'unsafe-inline' keyword, a hash ('sha256-KMUaZ90m3965NtgVdQEgBJ+vRuC6eApfiDK3GqExqs8='), or a nonce ('nonce-...') is required to enable inline execution.
```

```
Refused to frame 'https://td.doubleclick.net/' because it violates the following Content Security Policy directive: "frame-src 'self' 
```

**Comment by Christinadobrzyn** [comment]
Thanks for investigating @arosiclair! Let me know if you want me to add anyone to this GH. 

Just a heads up that I'm going to be ooo until Dec 30th. I'm not going to assign this to a BZ teammate but if anything is urgent, please reach out to the team for a volunteer.

**Comment by arosiclair** [comment]
It looks the the GTM script we use injects more JS scripts that trigger the `Refused to execute inline script`. The proper way to fix this is to generate and [inject a nonce](https://developers.google.com/tag-platform/security/guides/csp#enable_the_container_tag_to_use_csp) on the script. We tried something like that in the past but it didn't work well so it was reverted. 

I started another Cloudflare-Workers PR to implement nonce injection again but I'm having trouble running it in dev with this error:

```
--- 2024-12-26T20:39:22.407Z debug
*** Fatal uncaught kj::Exception: kj/compat/tls.c++:82: failed: OpenSSL error; message = error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
stack: 10180f74f 1018117cf 1009b376f 1009b5a5b 1009bd817 1009c154f 1009bfd5f 1009b1517 102e97983 102e97c93 102e9667f 102e96403 1009a07c7 190d24273
---

--- 2024-12-26T20:39:22.409Z debug
Error in ProxyController: Could not connect to InspectorProxyWorker
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/arosiclair/.npm/_npx/32026684e21afda6/node_modules/miniflare/dist/src/index.js:9985:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (/Users/arosiclair/.npm/_npx/32026684e21afda6/node_modules/miniflare/dist/src/index.js:3632:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
---
```

**Comment by arosiclair** [comment]
Alright I was able to fix the SSL error with `sudo` - `sudo npx wrangler dev index.js --local`. I also had to replace our `.dev.vars` with a new version to fix an error. This is almost looking good, but there still seems to be an issue with the nonce not getting propagated to the scripts that GTM injects.

**Comment by arosiclair** [comment]
> It looks like this might be the answer: https://stackoverflow.com/a/66573603

I was mistaken - this is unrelated. I realized we need to use the nonce-aware version of the GTM script given [here](https://developers.google.com/tag-platform/security/guides/csp). I tried it in dev, but it still doesn't clear up the CSP issue even though I can verify the nonce is getting set correctly on the injected scripts.

At this point, I think this is an issue internal to the GTM script that we cannot fix. Somebody else running into the same issue a few years ago experienced the same [here](https://support.google.com/tagmanager/thread/38946077?hl=en&msgid=44558897). 

I think I'll still push changes to inject the nonces and then we can just hope that Google fixes the issue upstream eventually. At the moment, GTM event tracking still works despite these errors so we should be able to ignore them in the meantime.

**Comment by Christinadobrzyn** [comment]
looks like this PR is in prod - https://github.com/Expensify/App/pull/54782

Are we working on another PR or should this be closed @arosiclair?

**Comment by arosiclair** [comment]
Oh yeah I still have [this PR](https://github.com/Expensify/Cloudflare-Workers/pull/163) which is still WIP. I'll get back to that soon.

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/Cloudflare-Workers/pull/163

**Comment by arosiclair** [comment]
https://github.com/Expensify/Cloudflare-Workers/pull/163 is ready for a review and testing. Just need a deployer to do so. Asked [here](https://expensify.slack.com/archives/C07J32337/p1738696831023649).

**Comment by arosiclair** [comment]
I had Rory review the PR. We agreed that we should fix the dev environment first so it's easier to test locally. That's gonna require a bit more time.

**Comment by arosiclair** [comment]
Dropping this to Monthly since this issue doesn't have any effects on the app beyond adding noise to the console.

**Comment by mallenexpensify** [comment]
👀 @kubabutkiewicz as you're working on console errors.

**Comment by kubabutkiewicz** [comment]
Thanks @mallenexpensify will take a look

**Comment by arosiclair** [comment]
No progress on this atm

**Comment by arosiclair** [comment]
Working on https://github.com/Expensify/App/issues/38072

**Comment by Christinadobrzyn** [comment]
watching - https://github.com/Expensify/App/issues/38072

**Comment by arosiclair** [comment]
Cloudflare Workers dev environment is fixed! Working on these two PRs now:

- https://github.com/Expensify/App/pull/63605
- https://github.com/Expensify/Cloudflare-Workers/pull/163

Also looking into issues that might be coming from GTM custom tags [here](https://expensify.slack.com/archives/C05F77PJ91V/p1749151975083199).

**Comment by Christinadobrzyn** [comment]
Hi @arosiclair just checking on this for a Melvin update.

**Comment by arosiclair** [comment]
Looks like the PRs are deployed now. I'm waiting to here from Spiralyze about the GTM custom tags.

**Comment by arosiclair** [comment]
Bumped Spiralyze

**Comment by arosiclair** [comment]
Alright we paused Spiralyze's custom tag. It looks like that cleaned up errors on staging! I'm still seeing some on production, but it's benign and seemingly can only be fixed upstream by Google:

```
Invalid URL: TypeError: Failed to construct 'URL': Invalid URL
    at eval (eval at w.<computed>.e (gtm.js?id=GTM-N4M3FLJZ:5:28), <anonymous>:1:71)
    at eval (eval at w.<computed>.e (gtm.js?id=GTM-N4M3FLJZ:5:28), <anonymous>:1:147)
    at w.<computed>.e (gtm.js?id=GTM-N4M3FLJZ:5:28)
    at qd.XK (gtm.js?id=GTM-N4M3FLJZ:627:632)
    at qd.<anonymous> (gtm.js?id=GTM-N4M3FLJZ:267:187)
    at k.invoke (gtm.js?id=GTM-N4M3FLJZ:173:362)
    at Ra (gtm.js?id=GTM-N4M3FLJZ:138:1120)
    at qd.evaluate (gtm.js?id=GTM-N4M3FLJZ:175:72)
    at qd.ze (gtm.js?id=GTM-N4M3FLJZ:202:455)
    at k.invoke (gtm.js?id=GTM-N4M3FLJZ:173:362)
```

So to recap we

1. Added more exceptions to our CSP
2. Started injecting nonces into our pages and used the nonce-aware version of the GTM script
3. Disabled Spiralyze's Custom HTML tag that fires when events are published

And with that, I think we're good to close for now!
