### ISSUE TITLE
UpdateProtectedBranch workflow is flaky

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#7403]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Lock a deploy checklist (or perform other actions that trigger deploys)

## Expected Result:
The workflow should not fail on the UpdateProtectedBranch workflow.

## Actual Result:
The UpdateProtectedBranch workflow fails intermittently and is flaky. I think we've seen this about a half dozen times, here is an example: https://github.com/Expensify/App/actions/runs/1747343828

## Workaround:
Re-run whatever workflow failed as a result of this.

## Platform:
GitHub Actions

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
Are we sure the PR exists? Like is it a race condition issue?

**Comment by AndrewGable** [comment]
Here are the logs:

```
Run futuratrepadeira/changed-files@1d252c611c64289d35243fc37ece7323ea5e93e1
  with:
    repo-token: ***
    pr-number: 7396
    pattern: .*
  env:
    SOURCE_BRANCH: version-PATCH-19e2158d07f99024cf864c54dda4acbf8b73e1ec
    NEW_VERSION: 1.1.33-0
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/futuratrepadeira/changed-files/1d252c611c64289d35243fc37ece7323ea5e93e1/dist/index.js:7956:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
Error: Unhandled error: HttpError: Not Found
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 25 Jan 2022 19:32:43 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '07C1:2084:989DF2:9E319A:61F0505B',
    'x-ratelimit-limit': '15000',
    'x-ratelimit-remaining': '14979',
    'x-ratelimit-reset': '1643142033',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '21',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/Expensify/App/pulls/7396/files?page=1&per_page=100',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.1.2 Node.js/12.13.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/pulls#list-pull-requests-files'
}
```

**Comment by roryabraham** [comment]
I don't recall seeing this recently.

**Comment by AndrewGable** [comment]
Ok let's reopen when if and when it happens again
