### ISSUE TITLE
Handle unknown fetch errors

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#8517]
# Problem

- Recently added a change that would log when an unknown error is handled by `HttpUtils.xhr()`
- Looks like there are quite a few errors that aren't being handled

# Solution 

Run down the list of errors and figure out how they can happen and what we should do about them

- [ ] `Network request failed`
- [ ] `NetworkError when attempting to fetch resource.`
- [ ] `The network connection was lost.`
- [ ] `Сетевое соединение потеряно.`
- [ ] `Nätverksanslutningen förlorades.`
- [ ] `cancelled`
- [ ] `cannot parse response`
- [ ] `Load failed`
- [ ] `Gateway Timeout`
- [ ] Empty string for `error.message` and this log... 🤔 

```
[alXt] ENSURE_BUGBOT unknown error caught while processing request ~~ command: 'Push_Authenticate' error: '' stack: '"Error\n at alert (address at index.android.bundle:1:785039)\n at anonymous (address at index.android.bundle:1:983362)\n at tryCallOne (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)\n at anonymous (/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)\n at apply (native)\n at anonymous (address at index.android.bundle:1:214637)\n at _callTimer (address at index.android.bundle:1:213536)\n at _callReactNativeMicrotasksPass (address at index.android.bundle:1:213740)\n at callReactNativeMicrotasks (address at index.android.bundle:1:215733)\n at __callReactNativeMicrotasks (address at index.android.bundle:1:120373)\n at anonymous (address at index.android.bundle:1:119458)\n at __guard (address at index.android.bundle:1:120214)\n at flushedQueue (address at index.android.bundle:1:119369)\n at callFunctionReturnFlushedQueue (address at index.android.bundle:1:119225)"' userAgent: 'okhttp/4.10.0-RC1'
```

For each of these we should...

- Figure out what it means
- Make sure the error is handled in the Network layer with the correct behavior

**Comment by marcaaron** [comment]
"Network request failed" looks like a [common React Native fetch error](https://react-native.canny.io/feature-requests/p/improve-typeerror-network-request-failed-error-message). Searching around on SO seems to imply it might be related to https and ssl certs. But that doesn't _quite_ make sense to me since I'd imagine no requests would work at all and not to see these random failures here and there.

**Comment by marcaaron** [comment]
Might help to also log what API endpoint is being used to verify we are using `https` though I'm positive we are.

**Comment by marcaaron** [comment]
After looking into all these errors I think they can for the most part be retried. However, I'm adding more logging for each specific error and whatever context in the code about what they might mean. Some are really cryptic errors and browser inconsistencies around what might be a "connection interrupted" type error.

**Comment by marcaaron** [comment]
Also realizing that it would be useful to log the status code of fetch errors when they throw so gonna open a PR for this.

**Comment by marcaaron** [comment]
These were all basically determined to be retry-able. We'll be logging for more specific errors in case any pop up that look important to investigate.
